package routes

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"nstudio/go-backend/internal/handlers"
	"nstudio/go-backend/internal/middleware"
	"nstudio/go-backend/internal/utils"
)

func Register(r *gin.Engine, app *handlers.App) {
	r.Use(middleware.Recovery())
	r.Use(middleware.CORS(app.Cfg))
	r.GET("/audio/*path", app.AudioFile)
	r.HEAD("/audio/*path", app.AudioFile)

	r.NoRoute(func(c *gin.Context) {
		utils.Error(c, http.StatusNotFound, "NOT_FOUND", "Route not found", nil)
	})

	api := r.Group("/api")
	api.GET("/health", app.Health)
	api.GET("/visitor", app.Visitor)
	api.GET("/voices", app.Voices)
	api.GET("/voices/preview", app.VoicePreview)
	api.HEAD("/voices/preview", app.VoicePreview)
	api.GET("/plans", app.Plans)

	auth := api.Group("/auth")
	auth.POST("/register", app.Register)
	auth.POST("/login", app.Login)
	auth.POST("/refresh", app.Refresh)
	auth.POST("/forgot-password", app.ForgotPassword)
	auth.POST("/reset-password", app.ResetPassword)
	auth.GET("/google/login", app.GoogleLogin)
	auth.GET("/google/callback", app.GoogleCallback)
	auth.POST("/verify-email-otp", app.VerifyEmailOTP)
	auth.POST("/resend-email-otp", app.ResendEmailOTP)
	authAuthed := auth.Group("", middleware.AuthRequired(app.DB, app.Cfg))
	authAuthed.GET("/me", app.Me)
	authAuthed.PATCH("/me", app.UpdateMe)
	authAuthed.PATCH("/password", app.UpdatePassword)
	authAuthed.POST("/logout", app.Logout)
	authAuthed.POST("/logout-all", app.LogoutAll)
	authAuthed.GET("/sessions", app.Sessions)
	authAuthed.DELETE("/sessions/:id", app.RevokeSession)
	authAuthed.POST("/totp/setup", app.TOTPSetup)
	authAuthed.POST("/totp/enable", app.TOTPEnable)
	authAuthed.POST("/totp/disable", app.TOTPDisable)
	authAuthed.POST("/2fa/setup", app.TOTPSetup)
	authAuthed.POST("/2fa/verify", app.TOTPEnable)
	authAuthed.POST("/2fa/disable", app.TOTPDisable)

	protected := api.Group("", middleware.AuthRequired(app.DB, app.Cfg))
	protected.GET("/dashboard/history", app.History)
	protected.GET("/notifications", app.Notifications)
	protected.PATCH("/notifications/:id/read", app.ReadNotification)
	protected.PATCH("/notifications/read-all", app.ReadAllNotifications)
	protected.DELETE("/notifications/:id", app.DeleteNotification)
	protected.DELETE("/notifications", app.ClearNotifications)
	protected.GET("/identity-verification/me", app.MyIdentity)
	protected.POST("/identity-verification/submit", app.SubmitIdentity)
	protected.GET("/verification/status", app.MyIdentity)
	protected.POST("/verification/submit", app.SubmitIdentity)
	protected.POST("/voice-clones", app.CreateVoiceClone)
	protected.GET("/voice-clones", app.ListVoiceClones)
	protected.PATCH("/voice-clones/:id", app.PatchVoiceClone)
	protected.DELETE("/voice-clones/:id", app.DeleteVoiceClone)
	protected.GET("/api/keys", app.ListAPIKeys)
	protected.POST("/api/keys", app.CreateAPIKey)
	protected.PATCH("/api/keys/:id", app.PatchAPIKey)
	protected.DELETE("/api/keys/:id", app.DeleteAPIKey)
	protected.POST("/api/keys/:id/regenerate", app.RegenerateAPIKey)
	protected.GET("/keys", app.ListAPIKeys)
	protected.POST("/keys", app.CreateAPIKey)
	protected.PATCH("/keys/:id", app.PatchAPIKey)
	protected.DELETE("/keys/:id", app.DeleteAPIKey)
	protected.POST("/keys/:id/regenerate", app.RegenerateAPIKey)
	protected.GET("/user/api-keys", app.ListAPIKeys)
	protected.POST("/user/api-keys", app.CreateAPIKey)
	protected.PATCH("/user/api-keys/:id", app.PatchAPIKey)
	protected.DELETE("/user/api-keys/:id", app.DeleteAPIKey)
	protected.POST("/user/api-keys/:id/regenerate", app.RegenerateAPIKey)
	protected.GET("/user/api-logs", app.UserAPILogs)
	protected.GET("/user/api-usage", app.UserAPIUsage)
	protected.GET("/webhooks", app.ListWebhooks)
	protected.POST("/webhooks", app.CreateWebhook)
	protected.PATCH("/webhooks/:id", app.PatchWebhook)
	protected.DELETE("/webhooks/:id", app.DeleteWebhook)
	protected.POST("/webhooks/:id/test", app.TestWebhook)
	protected.GET("/ws/notifications", app.NotificationWebSocket)

	v1 := api.Group("/v1", middleware.APIKeyOptional(app.DB), middleware.AuthOrExistingUser(app.DB, app.Cfg))
	v1.POST("/speech", app.CreateSpeech)
	v1.GET("/jobs/:id", app.GetJob)
	v1.GET("/jobs/:id/chunks", app.JobChunks)
	v1.POST("/jobs/:id/cancel", app.CancelJob)

	legacyJobs := api.Group("", middleware.AuthRequired(app.DB, app.Cfg))
	legacyJobs.POST("/generate", app.CreateSpeech)
	legacyJobs.POST("/jobs", app.CreateSpeech)
	legacyJobs.GET("/jobs", app.History)
	legacyJobs.GET("/jobs/:id", app.GetJob)
	legacyJobs.GET("/jobs/:id/chunks", app.JobChunks)
	legacyJobs.POST("/jobs/:id/cancel", app.CancelJob)
	legacyJobs.DELETE("/jobs/:id", app.DeleteJob)

	admin := api.Group("/admin", middleware.AuthRequired(app.DB, app.Cfg), middleware.AdminRequired())
	admin.GET("/summary", app.AdminSummary)
	admin.GET("/roles", app.AdminRoles)
	admin.GET("/credits", app.AdminCredits)
	admin.GET("/purchases", app.AdminPurchases)
	admin.GET("/voices", app.AdminVoices)
	admin.GET("/voice-clones", app.AdminVoiceClones)
	admin.GET("/users", app.AdminListUsers)
	admin.GET("/users/:id", app.AdminGetUser)
	admin.POST("/users", app.AdminCreateUser)
	admin.PATCH("/users/:id", app.AdminPatchUser)
	admin.DELETE("/users/:id", app.AdminDeleteUser)
	admin.PATCH("/users/:id/approve", app.AdminApproveUser)
	admin.PATCH("/users/:id/reject", app.AdminRejectUser)
	admin.PATCH("/users/:id/status", app.AdminUserStatus)
	admin.PATCH("/users/:id/role", app.AdminUserRole)
	admin.PATCH("/users/:id/plan", app.AdminUserPlan)
	admin.PATCH("/users/:id/credits", app.AdminUserCredits)
	admin.PATCH("/users/:id/api-access", app.AdminUserAPIAccess)
	admin.PATCH("/users/:id/voice-clones", app.AdminUserVoiceClones)
	admin.POST("/users/:id/resend-verification", app.AdminResendVerification)
	admin.POST("/users/:id/mark-email-verified", app.AdminMarkEmailVerified)
	admin.POST("/users/:id/reset-password-email", app.AdminResetPasswordEmail)
	admin.POST("/users/:id/logout-all", app.AdminLogoutAllUserDevices)
	admin.GET("/users/:id/identity-verification", app.AdminUserIdentityVerification)
	admin.PATCH("/users/:id/identity-verification", app.AdminPatchUserIdentityVerification)
	admin.GET("/users/:id/sessions", app.AdminUserSessions)
	admin.DELETE("/users/:id/sessions/:sessionId", app.AdminRevokeUserSession)
	admin.GET("/users/:id/api-keys", app.AdminUserAPIKeys)
	admin.DELETE("/users/:id/api-keys/:keyId", app.AdminRevokeUserAPIKey)
	admin.GET("/users/:id/activity-logs", app.AdminUserActivityLogs)
	admin.GET("/users/:id/purchases", app.AdminUserPurchases)
	admin.GET("/users/:id/voice-clones", app.AdminUserVoiceClonesList)
	admin.DELETE("/users/:id/voice-clones/:cloneId", app.AdminDeleteUserVoiceClone)
	admin.GET("/security/settings", app.AdminSecuritySettings)
	admin.PATCH("/security/settings", app.AdminPatchSecuritySettings)
	admin.GET("/security/logs", app.AdminSecurityLogs)
	admin.GET("/plans", app.AdminPlans)
	admin.POST("/plans", app.AdminCreatePlan)
	admin.PATCH("/plans/:id", app.AdminPatchPlan)
	admin.DELETE("/plans/:id", app.AdminDeletePlan)
	admin.GET("/identity-verifications", app.AdminIdentityList)
	admin.GET("/identity-verifications/:id", app.AdminIdentityGet)
	admin.PATCH("/identity-verifications/:id/approve", app.AdminIdentityApprove)
	admin.PATCH("/identity-verifications/:id/reject", app.AdminIdentityReject)
	admin.GET("/api-keys", app.AdminAPIKeys)
	admin.GET("/api-logs", app.AdminAPILogs)
	admin.GET("/audit-logs", app.AdminAuditLogs)
}
